export const PROJECTS = [
  {
    name: 'Tarie Cakes',
    desc: 'A full-featured bakery storefront for browsing artisan cakes, placing custom orders with personalized flavor and design options, and managing a shopping cart — all wrapped in a warm, inviting UI with smooth animations.',
    url: 'https://github.com/Tinashe623/Cake-store-project',
    homepage: 'https://tarie-cakes.vercel.app',
    tags: ['React', 'TypeScript', 'Chakra UI', 'Vite', 'Framer Motion'],
    image: '/images/projects/tarie-cakes-preview.png',
    gridArea: { base: 'auto', md: '1 / 1 / 2 / 3' },
  },
  {
    name: 'G.M.P Electrical',
    desc: 'Modern marketing platform for solar and electrical services featuring real-time quote generation and service showcase.',
    url: 'https://github.com/Tinashe623/gmp-electrical-solutions',
    homepage: 'https://gmp-electrical-solutions.vercel.app/',
    tags: ['React', 'Vite', 'Chakra UI'],
    featured: true,
    image: '/images/projects/gmp-preview.png',
    gridArea: { base: 'auto', md: '1 / 1 / 3 / 3' },
  },
  {
    name: 'Saeku Web Platform',
    desc: 'Modern web application for Saeku. Developed frontend components, user interfaces, and integrated with backend services.',
    url: 'https://github.com/farscorp/saeku-web-frontend',
    homepage: null,
    tags: ['React', 'Chakra UI', 'Frontend'],
    collaborative: true,
    role: 'Frontend Developer',
    team: 'Farscorp Team',
    image:
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '3 / 1 / 4 / 3' },
  },
  {
    name: 'Saeku Backend Services',
    desc: 'Backend infrastructure and API services for the Saeku platform. Contributed to service development and API integration.',
    url: 'https://github.com/farscorp/saeku-backend-services',
    homepage: null,
    tags: ['Backend', 'API', 'Services'],
    collaborative: true,
    role: 'Developer',
    team: 'Farscorp Team',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '3 / 3 / 4 / 5' },
  },

  {
    name: 'St James Zongoro Primary',
    desc: 'Official school website for St James Zongoro Primary School with admissions, events, and information portal.',
    url: 'https://github.com/Tinashe623/zongoro-primary',
    homepage: 'https://zongoro-primary.vercel.app/',
    tags: ['React', 'Vite', 'Chakra UI'],
    image: '/images/projects/st-james-zongoro-preview.png',
    inProgress: true,
  },
  {
    name: 'Reigns Hydraulics',
    desc: 'Professional hydraulics company website showcasing industrial services, products, and engineering solutions.',
    url: 'https://github.com/Tinashe623/reigns-hydraulics',
    homepage: 'https://reigns-hydraulics.vercel.app/',
    tags: ['React', 'Vite', 'Chakra UI'],
    image: '/images/projects/reigns-preview.png',
    inProgress: true,
  },
  {
    name: 'Exquisite Rubble Removal',
    desc: 'Professional rubble removal and site clearing services website with service showcase and contact information.',
    url: 'https://github.com/Tinashe623/exquisite-rubble-removal',
    homepage: 'https://exquisite-rubble-removal.vercel.app/',
    tags: ['React', 'Vite', 'Chakra UI'],
    image: '/images/projects/rubble-removal-preview.png',
    inProgress: true,
  },
  {
    name: 'Personal Portfolio',
    desc: 'Modern, aesthetically driven professional portfolio showcasing projects and skills with premium glassmorphism design.',
    url: 'https://github.com/Tinashe623/my-portfolio',
    homepage: 'https://tinashe-mundieta.vercel.app',
    tags: ['React', 'Vite', 'Chakra UI', 'Framer Motion'],
    image:
      'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&h=800&fit=crop&q=80',
  },
]
