export const PROJECTS = [
  {
    name: 'G.M.P Electrical',
    desc: 'Modern marketing platform for solar and electrical services featuring real-time quote generation and service showcase.',
    url: 'https://github.com/Tinashe623/gmp-electrical-solutions',
    homepage: 'https://gmp-electrical-solutions.vercel.app/',
    tags: ['React', 'Solar', 'Vite', 'Chakra UI'],
    featured: true,
    image: '/images/projects/gmp-preview.png',
    gridArea: { base: 'auto', md: '1 / 1 / 3 / 3' },
  },
  {
    name: 'Saeku Web Platform',
    desc: 'Modern web application for Saeku. Developed frontend components, user interfaces, and integrated with backend services.',
    url: 'https://github.com/farscorp/saeku-web-frontend',
    homepage: null,
    tags: ['React', 'Chakra UI', 'Frontend'],
    collaborative: true,
    role: 'Frontend Developer',
    team: 'Farscorp Team',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '3 / 1 / 4 / 3' },
  },
  {
    name: 'Saeku Backend Services',
    desc: 'Backend infrastructure and API services for the Saeku platform. Contributed to service development and API integration.',
    url: 'https://github.com/farscorp/saeku-backend-services',
    homepage: null,
    tags: ['Backend', 'API', 'Services'],
    collaborative: true,
    role: 'Developer',
    team: 'Farscorp Team',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '3 / 3 / 4 / 5' },
  },
  {
    name: 'Netflix Clone',
    desc: 'Netflix-style UI with hero section, content rows, and responsive cards.',
    url: 'https://github.com/Tinashe623/netfix-clone-rs',
    homepage: null,
    tags: ['React', 'CSS3', 'UI/UX'],
    inProgress: true,
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '1 / 3 / 2 / 5' },
  },
  {
    name: 'Todo App',
    desc: 'React Todo app with hooks, clean UI, and full CRUD functionality.',
    url: 'https://github.com/Tinashe623/Todo-App',
    homepage: 'https://tinashe-todo-app.vercel.app/',
    tags: ['React', 'Hooks', 'State'],
    image: '/images/projects/todo-preview.png',
    gridArea: { base: 'auto', md: '2 / 3 / 3 / 4' },
  },
  {
    name: 'Temperature Converter',
    desc: 'Instant temperature conversion with clean interface and validation.',
    url: 'https://github.com/Tinashe623/temperature-conversion-program',
    homepage: 'https://tinashe-temp-converter.vercel.app/',
    tags: ['JavaScript', 'DOM'],
    image: '/images/projects/temp-preview.png',
    gridArea: { base: 'auto', md: '2 / 4 / 3 / 5' },
  },
  {
    name: 'Digital Clock (Lumina Time)',
    desc: 'Premium Glassmorphism Digital Suite with clock, date, greetings, and precision stopwatch.',
    url: 'https://github.com/Tinashe623/Digital_clock',
    homepage: 'https://digital-clock-nine-taupe.vercel.app/',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
    image: '/images/projects/clock-preview.png',
    gridArea: { base: 'auto', md: '4 / 3 / 5 / 5' },
  },
  {
    name: 'Personal Portfolio',
    desc: 'Modern, aesthetically driven professional portfolio showcasing projects and skills with premium glassmorphism design.',
    url: 'https://github.com/Tinashe623/my-portfolio',
    homepage: 'https://tinashe-mundieta.vercel.app',
    tags: ['React', 'Vite', 'Chakra UI', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&h=800&fit=crop&q=80',
    gridArea: { base: 'auto', md: '5 / 1 / 6 / 3' },
  },
]
